######################################################################
# Automatically generated by qmake (2.01a) Mon Aug 20 13:50:02 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += data_collect.h
SOURCES += data_collect.c main.c
